// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 NatureSense

//! **Spec design actor** — convert a freeform, detailed spec into the strict
//! textual AppSpec.
//!
//! Interaction model (agreed with the product):
//!
//! - The input is a freeform but detailed spec, pasted into the editor or
//!   loaded from a document. **Convert** asks the LLM to rewrite it as the
//!   strict `spec.md` AppSpec grammar; the result is parsed + validated and
//!   displayed for approval.
//! - The freeform spec may be resubmitted (Convert again) any number of times
//!   until the generated AppSpec looks right.
//! - **Accept** validates the generated spec.md (errors block it), persists the
//!   derivation into the project memory graph, marks the session `Decided`, and
//!   records an accepted version. **Reopen** returns to the free-form phase so
//!   the spec can be changed and re-accepted.
//!
//! The LLM is injected as a plain async closure (like [`super::spec_gen`]), so
//! the actor is fully testable with canned scripts.

use serde::{Deserialize, Serialize};
use std::future::Future;
use std::pin::Pin;

use async_trait::async_trait;

use tokio::sync::{mpsc, oneshot};
use tracing::{info, warn};

use crate::actors::Actor;
use spire_core::models::memory_graph::AttrNode;
use spire_core::subsystems::graph::memory_graph::MemoryGraphMessage;

use super::spec::{validate, AppSpec, SpecIssue, SpecIssueSeverity};
use super::spec_graph;
use super::spec_md;

/// An injected LLM call: a convert prompt → the spec.md text (plain text
/// completion; the model is instructed to output only the AppSpec markdown).
pub type LlmCall = Box<
    dyn Fn(String) -> Pin<Box<dyn Future<Output = Result<String, String>> + Send>> + Send + Sync,
>;

/// Whether the design session is still being edited or has been accepted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DesignMode {
    /// The freeform spec can still be re-converted / edited.
    Freeform,
    /// An AppSpec was accepted; only Reopen is allowed.
    Decided,
}

/// One deterministic derivation recorded by an Accept press.
#[derive(Debug, Clone, Serialize)]
pub struct AcceptedSpec {
    pub version: u32,
    pub app_spec: AppSpec,
    pub issues: Vec<SpecIssue>,
    pub decided_at: chrono::DateTime<chrono::Utc>,
}

/// A point-in-time view of the design session.
#[derive(Debug, Clone, Serialize)]
pub struct SpecDesignState {
    pub mode: DesignMode,
    pub project_name: String,
    pub goal: String,
    /// The freeform spec last submitted to Convert (persisted).
    pub freeform_spec: String,
    /// The AppSpec markdown most recently generated by Convert (if any).
    pub spec_md: Option<String>,
    pub accepted: Vec<AcceptedSpec>,
    pub latest: Option<AppSpec>,
    /// Validation issues of the most recently generated spec (warnings + errors).
    pub last_issues: Vec<SpecIssue>,
}

/// Messages routed to the [`SpecDesignActor`]. Each carries its own typed reply
/// channel, following the crate's actor convention.
#[derive(Debug)]
pub enum SpecDesignMessage {
    Start {
        project_name: String,
        goal: String,
        /// false (default) resumes a persisted session; true starts fresh.
        reset: bool,
        reply_to: oneshot::Sender<Result<SpecDesignState, String>>,
    },
    /// Convert a freeform spec into the textual AppSpec. Returns the outcome
    /// (generated spec.md, parse error when the model output was unparseable,
    /// validation issues, and the updated state).
    Convert {
        spec_text: String,
        reply_to: oneshot::Sender<Result<ConvertOutcome, String>>,
    },
    /// Accept the currently generated AppSpec: validate, persist, mark decided.
    Accept {
        reply_to: oneshot::Sender<Result<AppSpec, String>>,
    },
    /// Return to free-form editing after an accept (Revise).
    Reopen {
        reply_to: oneshot::Sender<Result<SpecDesignState, String>>,
    },
    GetState {
        reply_to: oneshot::Sender<SpecDesignState>,
    },
}

/// Result of a Convert run, shaped for the UI: the generated markdown, whether
/// it parsed into an AppSpec, the validation issues (when it parsed), and the
/// full session state.
#[derive(Debug, Clone, Serialize)]
pub struct ConvertOutcome {
    pub spec_md: String,
    /// Present when the LLM output could not be parsed as an AppSpec.
    pub parse_error: Option<String>,
    /// Validation issues of the parsed spec (warnings + errors; empty when the
    /// output did not parse).
    pub issues: Vec<SpecIssue>,
    pub state: SpecDesignState,
}

/// Free-form-spec → AppSpec session. Created per project; holds the freeform
/// spec, the latest generated spec.md and the accepted AppSpecs.
pub struct SpecDesignActor {
    project_name: String,
    goal: String,
    llm: LlmCall,
    memory_graph_tx: Option<mpsc::Sender<MemoryGraphMessage>>,
    mode: DesignMode,
    freeform_spec: String,
    spec_md: Option<String>,
    accepted: Vec<AcceptedSpec>,
    latest: Option<AppSpec>,
    last_issues: Vec<SpecIssue>,
    /// Session-instance token, kept so a reset simply switches instance instead
    /// of deleting stale nodes.
    instance: String,
}

impl SpecDesignActor {
    /// A fresh, unconfigured session. The RPC entry always calls [`Self::start`]
    /// first, which fixes project + goal.
    pub fn new(llm: LlmCall) -> Self {
        Self {
            project_name: String::new(),
            goal: String::new(),
            llm,
            memory_graph_tx: None,
            mode: DesignMode::Freeform,
            freeform_spec: String::new(),
            spec_md: None,
            accepted: Vec::new(),
            latest: None,
            last_issues: Vec::new(),
            instance: String::new(),
        }
    }

    /// Wire the memory graph so an accepted AppSpec can be persisted.
    pub fn set_memory_graph(&mut self, tx: mpsc::Sender<MemoryGraphMessage>) {
        self.memory_graph_tx = Some(tx);
    }

    fn session_node_name(&self) -> String {
        self.project_name.clone()
    }

    /// Persist the session (freeform spec + generated AppSpec) as a
    /// `design_session` node so a Convert/Accept survives restarts. Best-effort
    /// — a missing graph keeps the session in-memory.
    async fn persist_session(&self) {
        let Some(mg_tx) = &self.memory_graph_tx else {
            return;
        };
        let props = |p: &[(&str, serde_json::Value)]| -> std::collections::HashMap<String, serde_json::Value> {
            p.iter().map(|(k, v)| (k.to_string(), v.clone())).collect()
        };
        let now = chrono::Utc::now();
        let session = AttrNode {
            id: uuid::Uuid::new_v4().to_string(),
            node_type: super::spec_persist::MG_NODE_TYPE.to_string(),
            subtype: Some(DS_SESSION.to_string()),
            name: self.session_node_name(),
            description: Some(self.goal.clone()),
            properties: props(&[
                ("goal", serde_json::json!(self.goal)),
                ("mode", serde_json::json!(mode_str(self.mode))),
                ("instance", serde_json::json!(self.instance)),
                ("freeform_spec", serde_json::json!(self.freeform_spec)),
                ("spec_md", serde_json::json!(self.spec_md)),
            ]),
            embedding_id: None,
            created_at: now,
            updated_at: now,
            version: 1,
        };
        if let Err(e) = merge_node(mg_tx, session).await {
            warn!(
                "[SpecDesign] session node persist failed for '{}': {e}",
                self.project_name
            );
        }
    }

    /// Restore a persisted session from the project graph for `project_name`.
    /// Returns true when a session node existed and was loaded.
    async fn resume_session(&mut self, project_name: &str) -> bool {
        let Some(mg_tx) = &self.memory_graph_tx else {
            return false;
        };
        let Ok(mut found) = query_nodes(
            mg_tx,
            Some(super::spec_persist::MG_NODE_TYPE),
            Some(DS_SESSION),
            Some(project_name),
            1,
        )
        .await
        else {
            return false;
        };
        let Some(session) = found.pop() else {
            return false;
        };
        let Some(instance) = session.str_prop("instance") else {
            return false;
        };
        let mode = match session.str_prop("mode").as_deref() {
            Some("decided") => DesignMode::Decided,
            _ => DesignMode::Freeform,
        };
        self.project_name = project_name.to_string();
        self.mode = mode;
        self.instance = instance.clone();
        self.freeform_spec = session
            .properties
            .get("freeform_spec")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        self.spec_md = session
            .properties
            .get("spec_md")
            .and_then(|v| v.as_str())
            .map(str::to_string);
        // accepted/latest are re-derived on the next Accept; keep the screen
        // honest by not claiming a version we cannot reconstruct here.
        self.accepted.clear();
        self.latest = None;
        self.last_issues.clear();
        info!(
            "[SpecDesign] resumed persisted session for '{}' (freeform={}B spec_md={}B, mode={:?})",
            self.project_name,
            self.freeform_spec.len(),
            self.spec_md.as_deref().map(str::len).unwrap_or(0),
            mode
        );
        true
    }

    /// Async entry used by the Start RPC: resume a persisted session unless a
    /// reset was requested.
    pub async fn start_session(
        &mut self,
        project_name: &str,
        goal: &str,
        reset: bool,
    ) -> Result<SpecDesignState, String> {
        if !reset && self.resume_session(project_name).await {
            self.goal = goal.to_string();
            return Ok(self.state());
        }
        let _ = self.start(project_name, goal);
        self.persist_session().await;
        Ok(self.state())
    }

    pub fn state(&self) -> SpecDesignState {
        SpecDesignState {
            mode: self.mode,
            project_name: self.project_name.clone(),
            goal: self.goal.clone(),
            freeform_spec: self.freeform_spec.clone(),
            spec_md: self.spec_md.clone(),
            accepted: self.accepted.clone(),
            latest: self.latest.clone(),
            last_issues: self.last_issues.clone(),
        }
    }

    fn require_session(&self) -> Result<(), String> {
        if self.project_name.is_empty() {
            Err("no spec-design session — call spec-design/start first".to_string())
        } else {
            Ok(())
        }
    }

    fn require_freeform(&self) -> Result<(), String> {
        if self.mode == DesignMode::Decided {
            Err(
                "already accepted — the AppSpec is frozen; Reopen to revise the freeform spec"
                    .to_string(),
            )
        } else {
            Ok(())
        }
    }

    /// (Re)start the session for a project/goal (fresh; the Start RPC uses
    /// [`Self::start_session`] which resumes a persisted one unless reset).
    pub fn start(&mut self, project_name: &str, goal: &str) -> Result<SpecDesignState, String> {
        self.project_name = project_name.to_string();
        self.goal = goal.to_string();
        self.mode = DesignMode::Freeform;
        self.freeform_spec.clear();
        self.spec_md = None;
        self.accepted.clear();
        self.latest = None;
        self.last_issues.clear();
        self.instance = uuid::Uuid::new_v4().to_string();
        info!(
            "[SpecDesign] session started for '{}': {}",
            self.project_name, self.goal
        );
        Ok(self.state())
    }

    /// Convert a freeform spec into the strict textual AppSpec via the LLM.
    /// Stores the freeform spec + generated markdown (persisted), parses +
    /// validates the result, and returns the outcome for review.
    pub async fn convert(&mut self, spec_text: &str) -> Result<ConvertOutcome, String> {
        self.require_session()?;
        let spec_text = spec_text.trim();
        if spec_text.is_empty() {
            return Err("empty spec — paste or write the freeform requirements first".to_string());
        }
        self.freeform_spec = spec_text.to_string();
        self.mode = DesignMode::Freeform;
        self.accepted.clear();
        let prompt = convert_spec_prompt(&self.project_name, &self.goal, spec_text);
        let raw = self.call_llm(prompt).await?;
        let spec_md = raw.trim().to_string();
        self.spec_md = Some(spec_md.clone());
        let (parse_error, issues) = match spec_md::markdown_to_spec(&spec_md) {
            Ok(app) => {
                let issues = validate(&app);
                self.latest = Some(app);
                self.last_issues = issues.clone();
                (None, issues)
            }
            Err(e) => {
                self.latest = None;
                self.last_issues.clear();
                (Some(e), Vec::new())
            }
        };
        self.persist_session().await;
        info!(
            "[SpecDesign] '{}' converted freeform spec ({} chars) -> spec_md ({} chars, parse_ok={})",
            self.project_name,
            self.freeform_spec.len(),
            spec_md.len(),
            parse_error.is_none()
        );
        Ok(ConvertOutcome {
            spec_md,
            parse_error,
            issues,
            state: self.state(),
        })
    }

    /// Accept the currently generated AppSpec (validate → persist → decided).
    pub async fn accept(&mut self) -> Result<AppSpec, String> {
        self.require_freeform()?;
        self.require_session()?;
        let Some(md) = self.spec_md.as_ref() else {
            return Err(
                "nothing to accept — convert the freeform spec into an AppSpec first"
                    .to_string(),
            );
        };
        let md = md.clone();
        self.accept_spec_markdown(&md).await
    }

    /// Validate a spec.md and, when valid, persist the graph derivation, mark
    /// the session decided, and record an accepted version.
    async fn accept_spec_markdown(&mut self, markdown: &str) -> Result<AppSpec, String> {
        let app: AppSpec = spec_md::markdown_to_spec(markdown)?;
        let issues = validate(&app);
        let errors: Vec<&SpecIssue> = issues
            .iter()
            .filter(|i| i.severity == SpecIssueSeverity::Error)
            .collect();
        if !errors.is_empty() {
            let detail = errors
                .iter()
                .map(|i| format!("  [{}] {}", i.path, i.message))
                .collect::<Vec<_>>()
                .join("\n");
            return Err(format!(
                "spec for '{}' does not validate — {} error(s):\n{detail}\nEdit the freeform spec and Convert again.",
                self.project_name,
                errors.len()
            ));
        }

        // Deterministic tail: persist the derivation (best-effort).
        if let Some(tx) = self.memory_graph_tx.clone() {
            let g = spec_graph::decompose(&app);
            let persisted =
                super::spec_persist::store_spec_graph(&tx, &self.project_name, &self.goal, &g)
                    .await;
            if persisted.is_none() {
                warn!(
                    "[SpecDesign] spec persisted without an anchor for '{}' (graph unavailable?)",
                    self.project_name
                );
            }
        }

        self.mode = DesignMode::Decided;
        self.last_issues = issues;
        self.latest = Some(app.clone());
        self.accepted.push(AcceptedSpec {
            version: self.accepted.len() as u32 + 1,
            issues: self.last_issues.clone(),
            app_spec: app.clone(),
            decided_at: chrono::Utc::now(),
        });
        self.persist_session().await;
        info!(
            "[SpecDesign] '{}' accepted — appspec v{} ({} types, {} actors, {} methods, {} screens)",
            self.project_name,
            self.accepted.len(),
            app.types.len(),
            app.actors.len(),
            app.bridge.len(),
            app.ui.len()
        );
        Ok(app)
    }

    /// Return to the free-form phase. The accepted spec stays recorded; the
    /// freeform spec can be changed and re-accepted.
    pub async fn reopen(&mut self) -> Result<SpecDesignState, String> {
        self.require_session()?;
        self.mode = DesignMode::Freeform;
        self.persist_session().await;
        info!(
            "[SpecDesign] '{}' reopened for free-form editing",
            self.project_name
        );
        Ok(self.state())
    }

    async fn call_llm(&self, prompt: String) -> Result<String, String> {
        (self.llm)(prompt)
            .await
            .map_err(|e| format!("LLM error: {e}"))
    }
}

/// Graph node subtype for the persisted design session.
pub const DS_SESSION: &str = "design_session";

fn mode_str(mode: DesignMode) -> &'static str {
    match mode {
        DesignMode::Freeform => "freeform",
        DesignMode::Decided => "decided",
    }
}

async fn merge_node(
    mg_tx: &tokio::sync::mpsc::Sender<MemoryGraphMessage>,
    node: AttrNode,
) -> Result<AttrNode, String> {
    let (t, r) = tokio::sync::oneshot::channel();
    mg_tx
        .send(MemoryGraphMessage::MergeAttrNode { node, reply_to: t })
        .await
        .map_err(|e| format!("memory graph channel closed: {e}"))?;
    r.await
        .map_err(|e| format!("merge reply lost: {e}"))?
        .map_err(|e| format!("merge failed: {e}"))
}

async fn query_nodes(
    mg_tx: &tokio::sync::mpsc::Sender<MemoryGraphMessage>,
    node_type: Option<&str>,
    subtype: Option<&str>,
    name: Option<&str>,
    limit: u32,
) -> Result<Vec<AttrNode>, String> {
    let (t, r) = tokio::sync::oneshot::channel();
    mg_tx
        .send(MemoryGraphMessage::QueryAttrNodes {
            node_type: node_type.map(str::to_string),
            subtype: subtype.map(str::to_string),
            name: name.map(str::to_string),
            limit: Some(limit),
            reply_to: t,
        })
        .await
        .map_err(|e| format!("memory graph channel closed: {e}"))?;
    r.await
        .map_err(|e| format!("query reply lost: {e}"))?
        .map_err(|e| format!("query failed: {e}"))
}

/// Injected at the top of the convert prompt so the model always designs
/// within the Spire stack instead of proposing arbitrary tech (Python/JS/web).
const SPIRE_APP_CONTEXT: &str = "SPIRE APP CONTEXT — always design within this.\n\
A Spire app is a native macOS application with a FIXED, non-negotiable stack:\n\
- UI: SwiftUI (macOS) — declarative screens.\n\
- Core: Rust, built on the actor pattern — isolated actors that own their state\n\
  and exchange typed messages over channels (no shared mutable state).\n\
- Integration: a JSON FFI bridge — actors expose named methods with typed\n\
  parameters and a typed result, called from SwiftUI.\n\
- Specification: the design is captured as a formal AppSpec with these sections:\n\
  * app    — project name + goal\n\
  * types  — shared records/enums referenced by actors, bridge and UI\n\
  * graph  — the memory-graph schema (nodes + edges) actors persist/query\n\
  * actors — the Rust side: each actor lists the bridge methods it handles\n\
  * bridge — the JSON method contract (method + params + result types)\n\
  * ui     — SwiftUI screens whose actions bind to bridge methods\n\
\n\
HARD CONSTRAINTS:\n\
- Design ONLY within the Spire stack: SwiftUI UI + Rust actors + the JSON\n\
  bridge + the AppSpec sections above.\n\
- Do NOT propose other languages or frameworks (Python, JavaScript, web/React,\n\
  Node, Flutter, Electron, or external servers/databases as the primary\n\
  backend).\n\
- The app's backend IS its own Rust actors; persistence is via the memory graph.\n\
- Project/crate naming convention: `spire-<name>`.";

pub const SPEC_MD_GRAMMAR: &str = r#"# AppSpec: <name>
**Goal**: <goal>

## Data types
### `Name` (record)
| field | type |
|-------|------|
| <field> | <type> |
### `Name` (enum)
A | B | C

## Graph
### nodes
- **NodeName** — <description>
  - <field>: <type>
### edges
| name | from | to | description |
|------|------|----|-------------|
| <edge> | <FromNode> | <ToNode> | <desc> |

## Backend
### `ActorName` — <description>
Handlers: <bridge method 1>, <bridge method 2>
State: <field>: <type>
Uses: <dependency>

## Bridge
### `method` — <description>
| param | type |
|-------|------|
| <param> | <type> |
Result: <type>

## UI
### <screenId> — Screen Title
Layout: vstack(text("..."), list(<item>), button("Save")->save, input("Name")@name, spacer)
Actions: <actionId>("label")-><bridgeMethod>   (or <actionId>-><bridgeMethod> when no label)
Bindings: <field><-<bridgeMethod>
Navigation: <actionId>-><screenId>

Type expressions: str | int | float | bool | <Name> | list<T> | T? | record(f:T;...)

Only include a section when the conversation actually decided it — never invent
content. Every UI action/binding/layout button must reference a ## Bridge method
and every bridge method must appear in exactly one actor's Handlers."#;

/// Prompt for the conversion step: rewrite the freeform spec as the strict
/// textual AppSpec, outputting only the markdown.
fn convert_spec_prompt(project_name: &str, goal: &str, freeform: &str) -> String {
    format!(
        "{SPIRE_APP_CONTEXT}\n\n\
         # Convert the freeform spec to an AppSpec\n\n\
         Project: {project_name}\n\
         Goal: {goal}\n\n\
         ## Freeform spec (source of truth — do not add requirements that are not\n\
         expressed here; resolve ambiguities with the most reasonable interpretation,\n\
         but only invent the minimum needed to make the AppSpec coherent)\n\
         {freeform}\n\n\
         SPEC GRAMMAR (strict, parseable 1:1):\n\
         {SPEC_MD_GRAMMAR}\n\n\
         Convert the freeform spec into the strict AppSpec grammar above. Only\n\
         include what the spec actually decides. Handlers listed in Backend and\n\
         methods called by UI actions must each exist in ## Bridge. Output ONLY\n\
         the spec markdown — no commentary, no code fences."
    )
}

#[async_trait]
impl Actor for SpecDesignActor {
    type Message = SpecDesignMessage;

    async fn handle(&mut self, msg: Self::Message) {
        match msg {
            SpecDesignMessage::Start {
                project_name,
                goal,
                reset,
                reply_to,
            } => {
                let _ = reply_to.send(self.start_session(&project_name, &goal, reset).await);
            }
            SpecDesignMessage::Convert { spec_text, reply_to } => {
                let _ = reply_to.send(self.convert(&spec_text).await);
            }
            SpecDesignMessage::Accept { reply_to } => {
                let _ = reply_to.send(self.accept().await);
            }
            SpecDesignMessage::Reopen { reply_to } => {
                let _ = reply_to.send(self.reopen().await);
            }
            SpecDesignMessage::GetState { reply_to } => {
                let _ = reply_to.send(self.state());
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::VecDeque;
    use std::sync::{Arc, Mutex};

    use super::super::spec_gen::example_gis_spec;

    fn canned(responses: Vec<String>) -> (LlmCall, Arc<Mutex<Vec<String>>>) {
        let prompts: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
        let prompts_for_call = prompts.clone();
        let queue: Arc<Mutex<VecDeque<String>>> =
            Arc::new(Mutex::new(responses.into_iter().collect()));
        let queue_for_call = queue.clone();
        let call: LlmCall = Box::new(move |prompt: String| {
            let prompts = prompts_for_call.clone();
            let queue = queue_for_call.clone();
            Box::pin(async move {
                prompts.lock().unwrap().push(prompt);
                let mut q = queue.lock().unwrap();
                let next = q.pop_front().or_else(|| q.back().cloned());
                Ok(next.unwrap_or_default())
            })
        });
        (call, prompts)
    }

    fn example_spec_md() -> String {
        spec_md::spec_to_markdown(&example_gis_spec())
    }

    fn actor(responses: Vec<String>) -> (SpecDesignActor, Arc<Mutex<Vec<String>>>) {
        let (llm, prompts) = canned(responses);
        (SpecDesignActor::new(llm), prompts)
    }

    #[test]
    fn start_and_convert_produce_a_parseable_appspec() {
        let (mut a, prompts) = actor(vec![example_spec_md()]);
        a.start("spire-gis", "view and edit map layers").unwrap();
        let out = pollster(a.convert("A map view for GIS features stored in the graph."))
            .unwrap();
        assert!(out.parse_error.is_none(), "{:?}", out.parse_error);
        assert_eq!(out.state.spec_md.as_deref(), Some(out.spec_md.as_str()));
        assert!(out.state.latest.is_some());
        let p = prompts.lock().unwrap()[0].clone();
        assert!(p.contains("## Freeform spec"));
        assert!(p.contains("SPEC GRAMMAR"));
        assert!(p.contains("## Data types"));
    }

    #[test]
    fn convert_reports_unparseable_model_output() {
        let (mut a, _) = actor(vec!["# Not a spec at all\n\nrandom".to_string()]);
        a.start("spire-gis", "view and edit map layers").unwrap();
        let out = pollster(a.convert("some vague idea")).unwrap();
        assert!(out.parse_error.is_some());
        assert!(out.state.latest.is_none());
        assert!(out.state.spec_md.is_some(), "raw model text is still kept");
        assert_eq!(out.state.mode, DesignMode::Freeform);
    }

    #[test]
    fn accept_persists_and_marks_decided_only_after_a_valid_convert() {
        let (mut a, _) = actor(vec![]);
        a.start("spire-gis", "view and edit map layers").unwrap();
        let err = pollster(a.accept()).unwrap_err();
        assert!(err.contains("convert"), "{err}");

        // Garbage conversion cannot be accepted (parse error is stored, accept
        // re-validates and fails).
        let (mut b, _) = actor(vec!["garbage".to_string()]);
        b.start("spire-gis", "view and edit map layers").unwrap();
        let _ = pollster(b.convert("idea")).unwrap();
        let err = pollster(b.accept()).unwrap_err();
        assert!(err.contains("does not validate") || err.contains("parse") || !err.is_empty());

        let (mut c, _) = actor(vec![example_spec_md()]);
        c.start("spire-gis", "view and edit map layers").unwrap();
        let out = pollster(c.convert("detailed gis spec")).unwrap();
        assert!(out.parse_error.is_none());
        let app = pollster(c.accept()).unwrap();
        assert_eq!(c.state().mode, DesignMode::Decided);
        assert_eq!(c.state().accepted.len(), 1);
        assert_eq!(app.types.len(), example_gis_spec().types.len());
    }

    #[test]
    fn reopen_allows_re_editing_after_accept() {
        let (mut a, _) = actor(vec![example_spec_md()]);
        a.start("spire-gis", "view and edit map layers").unwrap();
        pollster(a.convert("detailed spec")).unwrap();
        pollster(a.accept()).unwrap();
        assert_eq!(a.state().mode, DesignMode::Decided);
        pollster(a.reopen()).unwrap();
        assert_eq!(a.state().mode, DesignMode::Freeform);
    }

    /// Block on a future from a sync test (no global runtime needed).
    fn pollster<F: std::future::Future>(fut: F) -> F::Output {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(fut)
    }
}
