// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 NatureSense

//! **AppSpec codegen** — deterministic skeleton generation from a VALIDATED
//! [`AppSpec`].
//!
//! The bridge contract is the single source of truth, so everything below is a
//! *projection* of the spec — nothing is invented on either side:
//!
//! - `graph`  → typed graph accessors (sketched; bodies are filled later).
//! - `types`  → serde structs/enums (`types.rs`).
//! - `actors` → one skeleton per actor listing the bridge methods it handles.
//! - `bridge` → the FFI dispatch in `lib.rs` (routing DERIVED from the actors'
//!   `handlers`, never a separate route table) + typed Swift bridge wrappers.
//! - `ui`     → one SwiftUI screen skeleton per screen (layout + action hooks).
//!
//! Output is a flat list of [`GeneratedFile`]s written under the SpireApp
//! fill roots (`crates/<crate>/src`, `ui/swift/Sources`) — i.e. normal
//! `write_source_file` steps the existing fill pipeline can execute. Bodies
//! carry `TODO` markers: the next stage's LLM fill writes the real logic
//! inside the generated, validated contract.

use super::spec::{AppSpec, DomainType, LayoutNode, Type};

/// One generated file: fill-root-relative path + full content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Normalize a project name to a valid crate id (same rule as the scaffold):
/// lowercase, spaces → hyphens.
pub fn crate_id(project_name: &str) -> String {
    project_name.trim().to_lowercase().replace(' ', "-")
}

/// snake_case → PascalCase (Rust structs / Swift struct names).
fn pascal(s: &str) -> String {
    s.split(['_', '-', '/', ' '])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// The final segment of a bridge method (`map/listLayers` → `listLayers`)
/// camelCased, for Swift wrapper function names.
fn swift_method_id(method: &str) -> String {
    let last = method.rsplit('/').next().unwrap_or(method);
    let mut out = String::new();
    for (i, part) in last.split(['_', '-']).enumerate() {
        if i == 0 {
            out.push_str(part);
        } else {
            out.push_str(&pascal(part));
        }
    }
    out
}

/// Rust type text for a spec [`Type`] (used in serde struct fields).
fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Str => "String".to_string(),
        Type::Int => "i64".to_string(),
        Type::Float => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::List { of } => format!("Vec<{}>", rust_type(of)),
        Type::Option { of } => format!("Option<{}>", rust_type(of)),
        Type::Named { name } => name.clone(),
        // Skeleton-level placeholder for inline records; the LLM fill stage
        // replaces it with a real named type when it writes the method body.
        Type::Record { .. } => {
            "serde_json::Value // TODO(codegen): inline record — hoist to a named type".to_string()
        }
    }
}

// ── Rust: domain types (types.rs) ────────────────────────────────────────

fn render_types_rs(spec: &AppSpec) -> String {
    let mut out = String::from(
        "// Code-generated by spec_codegen.rs — bridge-derived domain types.\n\
         #![allow(dead_code)]\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    for t in &spec.types {
        match t {
            DomainType::Record { name, fields } => {
                out.push_str(&format!(
                    "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\npub struct {name} {{\n"
                ));
                for f in fields {
                    out.push_str(&format!("    pub {}: {},\n", f.name, rust_type(&f.ty)));
                }
                out.push_str("}\n\n");
            }
            DomainType::Enum { name, variants } => {
                out.push_str(&format!(
                    "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\npub enum {name} {{\n"
                ));
                for v in variants {
                    out.push_str(&format!("    {},\n", pascal(v)));
                }
                out.push_str("}\n\n");
            }
        }
    }
    out
}

// ── Rust: actor skeletons (actors.rs) ────────────────────────────────────

fn render_actors_rs(spec: &AppSpec) -> String {
    let mut out = String::from(
        "// Code-generated by spec_codegen.rs — one skeleton per AppSpec actor.\n\
         // Routing is derived: each actor lists the bridge methods it handles.\n\
         #![allow(dead_code)]\n\
         use serde_json::Value;\n\n",
    );
    for a in &spec.actors {
        let handlers = a.handlers.join("\", \"");
        out.push_str(&format!(
            "pub struct {};\n\nimpl {} {{\n    pub fn new() -> Self {{\n        Self\n    }}\n\n    /// Skeleton handler for the bridge methods this actor owns.\n    pub fn handle(&self, method: &str, params: &Value) -> String {{\n        let _ = (method, params);\n        // TODO({}): implement bodies for \"{}\".\n        serde_json::json!({{\"ok\": true, \"result\": null}}).to_string()\n    }}\n}}\n\n",
            pascal(&a.name),
            pascal(&a.name),
            a.name,
            handlers
        ));
    }
    out
}

/// The `match` arms of the FFI dispatch — every bridge method routed to the
/// actor whose `handlers` lists it (exactly-one-actor is validated upstream).
fn render_dispatch_arms(spec: &AppSpec) -> String {
    let mut out = String::new();
    for a in &spec.actors {
        if a.handlers.is_empty() {
            continue;
        }
        let arms: Vec<String> = a
            .handlers
            .iter()
            .map(|h| {
                format!(
                    "        \"{h}\" => actors::{}::new().handle(\"{h}\", &params),",
                    pascal(&a.name)
                )
            })
            .collect();
        out.push_str(&arms.join("\n"));
        out.push('\n');
    }
    out.push_str(
        "        _ => serde_json::json!({\"ok\": false, \"error\": \"unknown method\"}).to_string(),\n",
    );
    out
}

fn render_lib_rs(spec: &AppSpec, crate_name: &str) -> String {
    let dispatch = render_dispatch_arms(spec);
    format!(
        "//! {crate_name} — Rust core generated from a validated AppSpec.\n\
         //! FFI entry + dispatch are DERIVED from the AppSpec bridge contract\n\
         //! (routing by actor `handlers`); bodies are filled by the next stage.\n\
         #![allow(dead_code)]\n\
         \n\
         mod actors;\n\
         mod types;\n\
         \n\
         use std::ffi::{{CStr, CString}};\n\
         \n\
         /// Dispatch `{{\"method\": ..., \"params\": ...}}` to the owning actor.\n\
         fn dispatch(req: &str) -> String {{\n\
         \x20   let envelope: serde_json::Value = match serde_json::from_str(req) {{\n\
         \x20       Ok(v) => v,\n\
         \x20       Err(e) => {{\n\
         \x20           return serde_json::json!({{\"ok\": false, \"error\": format!(\"bad request: {{e}}\")}}).to_string();\n\
         \x20       }}\n\
         \x20   }};\n\
         \x20   let method = envelope.get(\"method\").and_then(|m| m.as_str()).unwrap_or(\"\");\n\
         \x20   let params = envelope.get(\"params\").cloned().unwrap_or(serde_json::json!({{}}));\n\
         \x20   match method {{\n\
         {dispatch}\
         \x20   }}\n\
         }}\n\
         \n\
         #[no_mangle]\n\
         pub extern \"C\" fn spire_send_json(request: *const std::os::raw::c_char) -> *mut std::os::raw::c_char {{\n\
         \x20   let req = unsafe {{ CStr::from_ptr(request) }}.to_string_lossy().to_string();\n\
         \x20   let reply = dispatch(&req);\n\
         \x20   CString::new(reply)\n\
         \x20       .map(|c| c.into_raw())\n\
         \x20       .unwrap_or(std::ptr::null_mut())\n\
         }}\n\
         \n\
         #[no_mangle]\n\
         pub extern \"C\" fn spire_free_string(p: *mut std::os::raw::c_char) {{\n\
         \x20   if !p.is_null() {{\n\
         \x20       unsafe {{ drop(CString::from_raw(p)) }};\n\
         \x20   }}\n\
         }}\n"
    )
}

// ── Swift: typed bridge wrappers (AppBridge.swift) ───────────────────────

fn render_app_bridge_swift(spec: &AppSpec) -> String {
    let mut out = String::from(
        "import Foundation\n\n\
         // Code-generated by spec_codegen.rs — one typed wrapper per AppSpec\n\
         // bridge method. All calls flow through CoreBridge.send (JSON FFI).\n\
         extension CoreBridge {\n",
    );
    for m in &spec.bridge {
        let id = swift_method_id(&m.method);
        out.push_str(&format!(
            "    /// {method}: {desc}\n    func {id}(params: [String: Any] = [:]) -> String? {{\n\
             \x20       let request: [String: Any] = [\"method\": \"{method}\", \"params\": params]\n\
             \x20       guard let data = try? JSONSerialization.data(withJSONObject: request),\n\
             \x20             let json = String(data: data, encoding: .utf8) else {{ return nil }}\n\
             \x20       // TODO(fill): decode the result into the typed contract.\n\
             \x20       return send(json)\n    }}\n",
            method = m.method,
            desc = m.description.trim(),
            id = id
        ));
    }
    out.push_str("}\n");
    out
}

/// The label of the first layout button referencing `action`, if any.
fn layout_button_label(layout: &LayoutNode, action: &str) -> Option<String> {
    match layout {
        LayoutNode::Button { label, action: a } if a == action => Some(label.clone()),
        LayoutNode::VStack { children } | LayoutNode::HStack { children } => {
            children.iter().find_map(|c| layout_button_label(c, action))
        }
        LayoutNode::List { item } => layout_button_label(item, action),
        _ => None,
    }
}

// ── Swift: screen skeletons (Screens.swift) ──────────────────────────────

fn render_screens_swift(spec: &AppSpec) -> String {
    let mut out = String::from(
        "import SwiftUI\n\n\
         // Code-generated by spec_codegen.rs — one screen skeleton per AppSpec\n\
         // ui screen. Buttons mirror the layout sketch's actions; bodies are\n\
         // TODO hooks for the fill stage.\n",
    );
    for s in &spec.ui {
        let struct_name = pascal(&s.id);
        out.push_str(&format!(
            "struct {struct_name}Screen: View {{\n    @Environment(CoreBridge.self) private var core\n\n    var body: some View {{\n",
        ));
        if s.actions.is_empty() {
            out.push_str("        // TODO(fill): no actions — layout sketch body\n");
        } else {
            out.push_str("        VStack {\n");
            for act in &s.actions {
                let wrapper = swift_method_id(&act.bridge);
                let label =
                    layout_button_label(&s.layout, &act.id).unwrap_or_else(|| act.id.clone());
                out.push_str(&format!(
                    "            // action \"{act_id}\" -> bridge method \"{bridge}\"\n\
                     \x20           Button(\"{label}\") {{ let _ = core.{wrapper}() }}\n",
                    act_id = act.id,
                    bridge = act.bridge,
                    label = label,
                    wrapper = wrapper
                ));
            }
            out.push_str("        }\n");
        }
        out.push_str("    }\n}\n\n");
    }
    out
}

// ── Orchestration ────────────────────────────────────────────────────────

/// Deterministic skeleton files for a validated spec, written under the
/// SpireApp fill roots.
pub fn generated_files(spec: &AppSpec, project_name: &str) -> Vec<GeneratedFile> {
    let crate_name = crate_id(project_name);
    vec![
        GeneratedFile {
            path: format!("crates/{crate_name}/src/types.rs"),
            content: render_types_rs(spec),
        },
        GeneratedFile {
            path: format!("crates/{crate_name}/src/actors.rs"),
            content: render_actors_rs(spec),
        },
        GeneratedFile {
            path: format!("crates/{crate_name}/src/lib.rs"),
            content: render_lib_rs(spec, &crate_name),
        },
        GeneratedFile {
            path: "ui/swift/Sources/SpireUI/AppBridge.swift".to_string(),
            content: render_app_bridge_swift(spec),
        },
        GeneratedFile {
            path: "ui/swift/Sources/SpireUI/Screens.swift".to_string(),
            content: render_screens_swift(spec),
        },
    ]
}

/// Map the generated skeleton files to `write_source_file` creation steps the
/// existing fill pipeline can execute.
pub fn codegen_steps(
    spec: &AppSpec,
    project_name: &str,
) -> Vec<super::project_creation::CreationStep> {
    use super::project_creation::{CreationStep, CreationStepType, StepStatus};
    generated_files(spec, project_name)
        .into_iter()
        .enumerate()
        .map(|(i, f)| CreationStep {
            id: format!("codegen-{}", i + 1),
            step_type: CreationStepType::WriteSourceFile,
            description: format!("Write {}", f.path),
            status: StepStatus::Pending,
            parameters: serde_json::json!({ "path": f.path, "content": f.content }),
            result: None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::subsystems::project::spec_gen::example_gis_spec;

    fn files(spec: &AppSpec, project_name: &str) -> Vec<GeneratedFile> {
        generated_files(spec, project_name)
    }

    fn content<'a>(fs: &'a [GeneratedFile], path: &str) -> &'a str {
        &fs.iter().find(|f| f.path == path).expect(path).content
    }

    #[test]
    fn output_is_deterministic_and_paths_sit_under_fill_roots() {
        let spec = example_gis_spec();
        let a = files(&spec, "spire-gis");
        let b = files(&spec, "spire-gis");
        assert_eq!(a, b, "codegen must be deterministic");
        for f in &a {
            let under_fill_root = f.path.starts_with("crates/") && f.path.ends_with(".rs")
                || f.path.starts_with("ui/swift/Sources/");
            assert!(under_fill_root, "path not under fill roots: {}", f.path);
            assert!(!f.content.is_empty());
        }
    }

    #[test]
    fn types_file_renders_records_and_enums() {
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let rs = content(&fs, "crates/spire-gis/src/types.rs");
        assert!(rs.contains("pub struct LayerInfo"));
        assert!(rs.contains("pub id: String"));
        assert!(rs.contains("pub visible: bool"));
    }

    #[test]
    fn actors_file_lists_handlers_per_actor() {
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let rs = content(&fs, "crates/spire-gis/src/actors.rs");
        assert!(rs.contains("pub struct MapActor"));
        assert!(rs.contains("map/listLayers"));
        assert!(rs.contains("map/addLayer"));
    }

    #[test]
    fn lib_dispatch_covers_every_bridge_method_and_routes_to_the_owning_actor() {
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let rs = content(&fs, "crates/spire-gis/src/lib.rs");
        for m in &spec.bridge {
            assert!(
                rs.contains(&format!("\"{}\" => actors::MapActor::new()", m.method)),
                "dispatch must route '{}' to MapActor\n{}",
                m.method,
                rs
            );
        }
        // No separate route list: each actor's handlers drive the match.
        assert!(rs.contains("match method"));
        assert!(rs.contains("unknown method"));
        assert!(rs.contains("spire_send_json"));
        assert!(rs.contains("spire_free_string"));
    }

    #[test]
    fn bridge_file_has_one_wrapper_per_method() {
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let sw = content(&fs, "ui/swift/Sources/SpireUI/AppBridge.swift");
        assert!(sw.contains("extension CoreBridge"));
        assert!(sw.contains("func listLayers(params: [String: Any] = [:]) -> String?"));
        assert!(sw.contains("\"method\": \"map/listLayers\""));
        assert!(sw.contains("func addLayer(params: [String: Any] = [:]) -> String?"));
        assert!(sw.contains("\"method\": \"map/addLayer\""));
    }

    #[test]
    fn screens_file_renders_a_view_per_screen_with_layout_labels() {
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let sw = content(&fs, "ui/swift/Sources/SpireUI/Screens.swift");
        assert!(sw.contains("struct MapScreen: View"));
        assert!(sw.contains("struct InspectorScreen: View"));
        // Layout sketch labels surface as the button labels.
        assert!(sw.contains("Button(\"Reload\") { let _ = core.listLayers() }"));
        assert!(sw.contains("Button(\"Add layer\") { let _ = core.addLayer() }"));
        // Every action is bound to its bridge method.
        assert!(sw.contains("action \"load\" -> bridge method \"map/listLayers\""));
        assert!(sw.contains("action \"add\" -> bridge method \"map/addLayer\""));
    }

    #[test]
    fn codegen_steps_are_executable_write_source_steps() {
        use super::super::project_creation::{CreationStepType, StepStatus};
        let spec = example_gis_spec();
        let fs = files(&spec, "spire-gis");
        let steps = codegen_steps(&spec, "spire-gis");
        assert_eq!(steps.len(), fs.len());
        for (i, step) in steps.iter().enumerate() {
            assert_eq!(step.id, format!("codegen-{}", i + 1));
            assert_eq!(step.step_type, CreationStepType::WriteSourceFile);
            assert_eq!(step.status, StepStatus::Pending);
            assert!(
                step.parameters.get("path").is_some() && step.parameters.get("content").is_some(),
                "step params must carry path + content"
            );
        }
    }

    #[test]
    fn layout_label_lookup_finds_nested_buttons() {
        let layout = LayoutNode::VStack {
            children: vec![
                LayoutNode::Text {
                    text: "heading".to_string(),
                },
                LayoutNode::List {
                    item: Box::new(LayoutNode::Button {
                        label: "Open".to_string(),
                        action: "open".to_string(),
                    }),
                },
            ],
        };
        assert_eq!(
            layout_button_label(&layout, "open").as_deref(),
            Some("Open")
        );
        assert_eq!(layout_button_label(&layout, "missing"), None);
    }
}
